### ISSUE TITLE
CLI Panic service apply

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#150]
```
panic: open user-data.yml: no such file or directory

goroutine 1 [running]:
panic(0x343a80, 0xc42007dc50)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
main.LoadFile(0xc42007be60, 0x10, 0xc4201304b0, 0xc4200de640)
	/Users/kumulo/tmp/ernest-cli/defintion.go:45 +0x130
main.LoadMapSlice(0xc4200d2a00, 0x9, 0x10, 0xc4200de760, 0x1, 0x18)
	/Users/kumulo/tmp/ernest-cli/defintion.go:56 +0x27b
main.LoadSlice(0xc4201303a0, 0x1, 0x1, 0xc4200de830, 0xc420133601, 0x1)
	/Users/kumulo/tmp/ernest-cli/defintion.go:75 +0x148
main.LoadMapSlice(0xc4200d2c00, 0x9, 0x10, 0xc420115220, 0x0, 0x0)
	/Users/kumulo/tmp/ernest-cli/defintion.go:60 +0x3b6
main.(*Definition).LoadFileImports(0xc420115220)
	/Users/kumulo/tmp/ernest-cli/defintion.go:31 +0x40
main.(*Manager).Apply(0xc42007bc50, 0xc4200ba4d0, 0xa4, 0x7fff5fbffab1, 0x1e, 0xc3901, 0x3a0af9, 0x4, 0xc420076600, 0xc420076600)
	/Users/kumulo/tmp/ernest-cli/manager_service.go:141 +0x20b
main.glob..func22(0xc4200c0c80, 0x0, 0xc4200c0c00)
	/Users/kumulo/tmp/ernest-cli/service_controller.go:68 +0xf3
github.com/urfave/cli.HandleAction(0x339760, 0x3d18a0, 0xc4200c0c80, 0xc420076600, 0x0)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/app.go:483 +0xb9
github.com/urfave/cli.Command.Run(0x3a0e4f, 0x5, 0x0, 0x0, 0x535530, 0x1, 0x1, 0x3abea5, 0x21, 0x0, ...)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/command.go:198 +0xcfb
github.com/urfave/cli.(*App).RunAsSubcommand(0xc420081d40, 0xc4200c0a00, 0x0, 0x0)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/app.go:374 +0xb21
github.com/urfave/cli.Command.startApp(0x3a1988, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3a9175, 0x1b, 0x0, ...)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/command.go:285 +0x82c
github.com/urfave/cli.Command.Run(0x3a1988, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3a9175, 0x1b, 0x0, ...)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/command.go:79 +0x17dc
github.com/urfave/cli.(*App).Run(0xc420081ba0, 0xc420078140, 0x4, 0x4, 0x0, 0x0)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/app.go:245 +0x723
main.main()
	/Users/kumulo/tmp/ernest-cli/main.go:32 +0x345
```

**Comment by adriacidre** [comment]
Additionally file inclusion doesn't work if you're not on the template directory, so you're not able to run something like
```
ernest-cli service apply ~/examples/tmp.yml
```
