### ISSUE TITLE
CLI raw error when ernest server is not running

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#416]
When the ernest server is not responding ernest-cli displays the following error, we should catch these errors and notify the user.

```
 kumulo@Adrias-MBP  ~/tmp/supu   master  ernest-cli user list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x12d26cc]

goroutine 1 [running]:
github.com/ernestio/ernest-cli/manager.(*Manager).ListUsers(0xc420112120, 0xc4200bc370, 0xa4, 0xc4200527d0, 0x1010712, 0xc4200e33c0, 0x20, 0x18)
	/Users/kumulo/flow/go/src/github.com/ernestio/ernest-cli/manager/user.go:19 +0x13c
github.com/ernestio/ernest-cli/command.glob..func36(0xc420094c80, 0x0, 0xc420094c80)
	/Users/kumulo/flow/go/src/github.com/ernestio/ernest-cli/command/user.go:36 +0x68
github.com/urfave/cli.HandleAction(0x137ebc0, 0x1408720, 0xc420094c80, 0xc42001c800, 0x0)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/app.go:485 +0xd4
github.com/urfave/cli.Command.Run(0x13f0529, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13f6766, 0x15, 0x0, ...)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/command.go:207 +0xb72
github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200a6680, 0xc420094a00, 0x0, 0x0)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/app.go:374 +0xacc
github.com/urfave/cli.Command.startApp(0x13f05a5, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13f7e01, 0x18, 0x0, ...)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/command.go:293 +0x8a3
github.com/urfave/cli.Command.Run(0x13f05a5, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13f7e01, 0x18, 0x0, ...)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/command.go:93 +0x14c7
github.com/urfave/cli.(*App).Run(0xc4200a64e0, 0xc4200101b0, 0x3, 0x3, 0x0, 0x0)
	/Users/kumulo/flow/go/src/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/Users/kumulo/tmp/ernest-cli/main.go:39 +0x4bd
```

**Comment by g3kk0** [comment]
Fixed ernestio/ernest-cli#84
