### ISSUE TITLE
Composable generate and unexisting folder

### ISSUE THREAD

**Issue by adriacidre** [ernestio/ernest#860]
Composable generate is throwing an uncomprensible error when destination folder does not exist.
```
composable generate -G develop definition.yml template.yml

cloning repos:
  compliance
  mfa
  definition-mapper
  all-all-azure-connector
  all-all-fake-connector
  authorization-store
panic: could not clone repo authorization-store

goroutine 25 [running]:
github.com/r3labs/composable/build.CloneRepos.func1(0xc42001afd0, 0xf, 0xc4201a0910, 0xc4201c7730, 0x7)
	/Users/kumulo/flow/go/src/github.com/r3labs/composable/build/clone.go:27 +0x32c
created by github.com/r3labs/composable/build.CloneRepos
	/Users/kumulo/flow/go/src/github.com/r3labs/composable/build/clone.go:21 +0x9b
```

Make composable to gracefully fail with a comprensible error message

**Comment by adriacidre** [comment]
PR: https://github.com/r3labs/composable/pull/12
